/*
 * CAN_configuration.h
 *
 *  Created on: Mar 15, 2022
 *      Author: Mohy
 */

#ifndef CAN_CONFIGURATION_H_
#define CAN_CONFIGURATION_H_


#define CAN_AUTO_BUS_OFF_CFG					CAN_AUTO_BUS_OFF
#define CAN_AUTO_WAKEUP_CFG						CAN_NO_AUTO_WAKEUP
#define CAN_AUTO_RETRANSMISSION_CFG				CAN_AUTO_RETRANSMISSION
#define CAN_OVER_RUN_BEHAVIOR_CFG				CAN_OVRUN_DISCARD
#define CAN_TRANSMIT_PRIORITY_CFG  				CAN_ID_PRIORITY


#endif /* CAN_CONFIGURATION_H_ */
